### ISSUE TITLE
Cannot receive any data when the program runs to "recvfrom"

### ISSUE THREAD

**Issue by lkzcswq** [adanmoran/ars430-ros-driver#2]
Hello! I use your project to receive data from ARS430 by UDP multicast. Firstly I use "tcpdump" to grab the data package and the data from Radar can be seen. However, when I start the rosudp node, there is nothing to receive. I don't know whether MCAST_GRP  and MCAST_PORT are wrong. May I ask you if
Source IP : ?                                 Source Port : ?
Destination IP : 255.0.0.1             Destination Port : 31122
Host IP:'192.168.1.30'
Thank you for your help!

**Comment by adanmoran** [comment]
Hi Weiqi,

I don't provide support for this package, as it was developed several years
ago and is no longer maintained.

However, I can tell you that you need to set your source IP and ports to
that of the ARS430 radar (the radar's IP must be 192.168.1.2). You can also
test the behaviour with the test scripts provided.

Best of luck,
Adan
